resources:
  - namespace.yaml
  - appsody-subscription.yaml
  - monitoring-operator-group.yaml
  - service-binding-operator-source.yaml
  - service-binding-subscription.yaml
  - strimzi-subscription.yaml
  - prometheus-subscription.yaml
