apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: strimzi
spec:
  serviceMonitorSelector:
    matchLabels:
      app: strimzi
  serviceMonitorNamespaceSelector:
    matchNames:
      - coffeeshop
