apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-serviceaccount
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus-serviceaccount
  # additionalScrapeConfigs: # Removing the additional config for testing purposes
  #   name: prometheus-config-secrets
  #   key: prometheus-additional-config.yaml
