apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-clusterrolebinding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: prometheus-serviceaccount
    namespace: coffeeshop-monitoring
