apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafana-datasource
spec:
  name: grafana-datasources.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      url: 'https://prometheus-operated.openshift-user-workload-monitoring.svc.cluster.local:9091/'
      access: proxy
      basicAuth: false
      withCredentials: false
      isDefault: true
      editable: true
      jsonData:
        httpHeaderName1: "Authorization"
        tlsSkipVerify: true
      secureJsonData:
        httpHeaderValue1: "Bearer [TOKEN]"
---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  ingress:
    enabled: true
  config:
    security:
      admin_user: "root"
      admin_password: "secret"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: False
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
